language: cpp
sudo: false

matrix:
  include:

    # Linux C++14 GCC builds
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: CXX_EVAL="g++-7" CC_EVAL="gcc-7" BUILD_TYPE='Release'

    - os: linux
      compiler: gcc
      addons: *gcc7
      env: CXX_EVAL="g++-7" CC_EVAL="gcc-7" BUILD_TYPE='Debug'

before_install:
  - export CXX=$CXX_EVAL
  - export CC=$CC_EVAL
  - export CXXFLAGS="-Werror"

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.4-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      which cmake || brew install cmake
    fi
before_script:
  - which $CXX
  - $CXX --version

  - cd ..
  - cmake -H. -BBuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - cd Build

script:
  - make -j 2
